apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
  namespace: oracle-oke-app
spec:
  revisionHistoryLimit: 1
  replicas: 1
  selector:
    matchLabels:
      app: frontend-oke-app
  template:
    metadata:
      labels:
        app: frontend-oke-app
    spec:
      containers:
        - name: frontend-oke-app
          image: dokkaushik/frontend-oke-app:909dacff23d3b60b7dd07c7eff3752f010d338f4
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20
